### ISSUE TITLE
Fix re-subscribe issue

### ISSUE THREAD

**Issue by DirtyAnalytics** [segmentio/integration-mailchimp#13]
Right now every time people call `identify` users get re-subscribed to the Mailchimp list.

We should either keep Mailchimp as `Mailchimp: false` by default so people can choose when to opt in, or some other fix here.

**Comment by DirtyAnalytics** [comment]
@sperand-io @lambtron @stevenmiller888 any ideas here?

**Comment by DirtyAnalytics** [comment]
the other option would be an event mapper that triggers the subscribe which would probably relate to spec actually @ndhoule

**Comment by glenngillen** [comment]
Thanks for tracking this. The only two approaches that come to mind are:

- Somehow decouple `identify` conceptually from a "signup". Maybe an extra flag? An extra method seems a bit overkill, and assuming it based on some delta from `createdAt` would be neat but maybe a bit too magic.
- I haven't fully grokked how the new "Tracking Plan" feature works, and the `identify` bit doesn't appear to be enabled. But if there was scope to say "Send to this integration at most 1 time per user" that'd solve it.

**Comment by pauloschilling** [comment]
@glenngillen This "Send to this integration at most 1 time per user" thing may prevent the customer traits (merge_vars) to be updated on MailChimp as well, causing even more trouble. :(

There's something that may work, but will require an extra call: you can check the `lists/member-info` to first see if it's a new user, then you be able to decide if `identify` should trigger `lists/subscribe` (new users) or `lists/update-member` (existent users).

I don't know what is your policy about reading external data, since it's definitely will increase the time needed to identify the customer.

**Comment by glenngillen** [comment]
@pauloschilling ah, I obviously hadn't considered the updating of merge vars. 

Having to make sure anyone who calls `identify` first calls `lists/member-info` and changes accordingly would mean writing my own abstraction on the segment libs to ensure it's always done correctly. At which point it's probably easier to just remove the integration and interface with Mailchimp directly. Which is what I'll likely have to do in the interim anyway.

**Comment by pauloschilling** [comment]
@glenngillen my suggestion was to made this change here https://github.com/segmentio/integration-mailchimp/blob/master/lib/index.js#L46, where today they do just a `.post('lists/subscribe.json')`, this way Segment's users will have to do nothing. :)

But this was just a suggestion, it really depends on what Segment's team is able to do.

Best!

**Comment by pauloschilling** [comment]
You can also just try to change the identify implementation to always do a `lists/update-member`, if it returns the "email not found" response, assume it's a new customer and call the `lists/subscribe`.

This way you can avoid the extra member info call, and will always do just one call for existent customers.

**Comment by glenngillen** [comment]
So circling back on this based on recent experience. I don't think either of the proposed solutions here would work in the instance where a customer deliberately decided to not confirm the double opt-in link because they didn't want to be on the list. As a result, every time they logged in I was attempting to re-subscribe them to something they had no desire to be on. Obviously a terrible experience :(

I'm left with no suggestions on how this might ever conceptually work with Segment and having to treat Mailchimp as a special case separately in only the signup flow.

**Comment by hankim813** [comment]
This has been fixed after we upgraded to Mailchimp's 3.0 API
