### ISSUE TITLE
Traits with underscores are not recorded in MailChimp

### ISSUE THREAD

**Issue by anark** [segmentio/integration-mailchimp#14]
If you have a mailchimp merge tag that contains an underscore it is not possible to add this trait using identify.

For example if you have mailchimp merge tag of WEEK_CPC it will not be recorded as it is sent to mailchimp as WEEK CPC.

**Comment by pauloschilling** [comment]
Actually, merge tags with "_" are now received by MailChimp with the "_" replaced by nothing.

"display_name" is received as "DISPLAYNAM", instead of "DISPLAY_NA" as before. Please note that it's also automatically truncated to 10 chars by Segment's library.

This caused our integration to broke, and we're now wondering if Segment is really the right choice to do the job.

**Comment by hankim813** [comment]
This has been now fully documented here

https://segment.com/docs/integrations/mailchimp/#recording-custom-user-traits
