### ISSUE TITLE
General concerns about this integration, and how to update the email_address for a list member

### ISSUE THREAD

**Issue by pauloschilling** [segmentio/integration-mailchimp#21]
Guys, I'm really concerned on how this integration have been maintained since I started using Segment and MailChimp.

At the moment when #4 was fixed everything seemed to be working just fine, but as you can see on #14, something went wrong and "_" on custom traits started to be ignored when translated to MC, causing our original configuration to fail and requiring us to rename the merge tags in MailChimp. This affected our service when it was only in staging for validation, not yet deployed to production.

Ok, everything was working fine again, but some extra changes have been made since 31153dc / afc22ab, I guess, causing the integration to not properly update existent members in MailChimp. Around 10 days later, 15d31b8 / ba7ab4d appeared to fix this issue. Unfortunately, this affected our production environment, and I still need to check if it was really solved.

1. Since all the code you produce follow the best practices and have CI/tests, don't you think that there's something wrong in the process?

2. Assuming that even the CI/tests can pass, do you have a QA team manually testing each integration before deploying any changes to production?

Really appreciate if you can provide any thoughts on this.

Thanks,
-Paulo

**Comment by hankim813** [comment]
Hey @pauloschilling ,

Thanks for the note here. I apologize for this integration's rocky behavior recently as we were migrating to Mailchimp's new 3.0 API. The newest PR today adds more testing and should close some loops regarding the updating of user profiles. 

1) You have a good point that if Circle CI passed but integrations still have issues, it should signify that we're lacking better testing. 
2) Currently we do not have a dedicated QA team manually testing each integration on a regular basis but the person in charge of deploying fixes should make sure the tests they wrote covers these cases. They are also expected to manually test the new changes and check that it is indeed showing/updating data in our testing account for that tool.

With that said, I spent a good deal of time doing manual QA myself, from trying to subscribe new users, to updating existing users, overriding listId, and repeating those steps given different setting options such as the double opt in. 

I QA'd the new changes quite a bit and everything worked for me as expected. I also made updates to the docs as well. I apologize for not getting it right the first time, there were some hidden nuances in Mailchimp's docs that I missed :(

I'll do my best to prevent that from happening again.

Let me know if you are still having issues with this integration -- you can email us at friends@segment.com and drop my name (Han) and I'll be able to provide deeper support. 

Thanks!
Han

**Comment by pauloschilling** [comment]
Hi @hankim813, thank you so much for the fast response and attentiveness.

You've been doing an amazing work making Segment the right choice to easily integrate a huge number of services, and I truly believe that it is really hard to keep every integration updated and fully functional. Thanks for that!

Also, I hope you can find the best way to avoid these situations, since even the small ones, compared to the entire work you do, may cause some hassles to your customers, but is noticeable that you're committed to this.

I did some tests here and everything seems to be working fine again, from sending a new list member to updating it with `boolean` traits.

I'm closing this. :)

Best,
-Paulo

**Comment by pauloschilling** [comment]
@hankim813, please allow me to reopen this to talk about updating an email address in MailChimp. I don't want to create a new issue right now because I'm not sure if we really need it.

Previously, I was able to identify an user sending these traits to update an email in MailChimp:
```json
{ "user_id": 123456, "email": "my_old@email.com", "new-email": "new@email.com", "..." }
```

> https://apidocs.mailchimp.com/api/2.0/lists/subscribe.php
> `merge_vars` > `new-email` = set this to change the email address.

I'm still sending the same traits, but the process is not updating the MC profile with the new email address anymore.

MC now uses a hashed email as an ID, so I was wondering if maybe you should implement something like this:

1. If we call `identify` with just an `email` as a trait, then you hash this email to use as the ID, also mapping it to `email_address` MC field *(just like the way you are doing today)*;

2. If we call `identify` with both an `email` and a `new_email` as traits, then you hash the `email` to use as the ID (as usual), mapping the `new_email` to `email_address` MC field.

What do you think? If you have any ideas, or if there's another solution available, please, just let me know.

Thanks,
-Paulo

**Comment by hankim813** [comment]
@pauloschilling hmm, did you create `new_email` as a merge trait? What did you name it as? It should have the label NEWEMAIL since that's what we should be sending it as. We strip out spaces and special characters. Can you confirm that you have done this?

**Comment by pauloschilling** [comment]
Hi @hankim813, the `new-email` is a reserved merge var used by `subscribe` method (API v2):
> https://apidocs.mailchimp.com/api/2.0/lists/subscribe.php
> merge_vars > new-email = set this to change the email address.

We don't need to store this "new email" in our list, MailChimp API always handled the update automatically, but now that you have mentioned, indeed the spaces/special chars stripping may prevent this from working with API v2 as well, and I think that API v3 does not provide such reserved merge var, also, Segment is using the `updateMember` now, instead of the `subscribe(update_existing=true)` as before.

Have you ever tried to update the `email_address` from a MailChimp list member using Segment's implementation? I truly believe that we may need to do something like I mentioned above: `{ id: hash(email), email_address: newEmail || email }`.

**Comment by hankim813** [comment]
@pauloschilling ahh I see what you mean now. I'll have to talk with our Integrations lead @sperand-io about this and get back to you!

**Comment by pauloschilling** [comment]
Hello @hankim813, @sperand-io, I was wondering if you guys have any news on this? Thanks!

**Comment by hankim813** [comment]
@pauloschilling hey I'm sorry for the delay -- Chris is out of office this week so we won't be able to look at it until next week :(

**Comment by pauloschilling** [comment]
No problem, @hankim813! I'm looking forward to hearing from you guys.

**Comment by sperand-io** [comment]
hey @pauloschilling! thanks for your patience mate, appreciate it.

looks like we're using the `userId` as the [`unique_email_id`](https://github.com/segmentio/integration-mailchimp/blob/master/lib/mapper.js#L34-L36) key, and the hashed email `id` is passed in the URL itself of the `PATCH` request to update an existing user.

Unfortunately, in making their API more strictly RESTful, they've also made it less user friendly for basic subscriber operations. They no longer have the `update_existing` distinction — you signify that by using `patch` rather than `post`, requiring us to first `get` member info and choosing from there whether to create or update.

![](https://cloudup.com/criRIllTvKQ+)

In their [docs](http://kb.mailchimp.com/api/article/how-to-manage-subscribers#Update-an-Address) they note that `email_address` is **read-only**, so unfortunately your proposed solution though smart wouldn't be a legal operation, and in absence of any clear documentation or spec on something like the old `new_email` field, we don't have much recourse here :/

Would you mind reaching out to them directly to ask how to accomplish this via their API v3? I'll have a go as well — as soon as we have clear docs/word from them we'll be happy to add support!

**Comment by pauloschilling** [comment]
Hi @sperand-io, really appreciate your attention here.

I'll definitely be reaching out to them, but I need to confess that I don't have any hope, this move they took by using the hash(email) as an ID seems to unveil a desire to make the email address the major identity, something immutable, and they will probably recommend a `subscribe(new_email + full_data)` + `unsubscribe(old_email)` instead of just updating the address. Let's cross our fingers!

Thank you, Chris, best!

**Comment by pauloschilling** [comment]
Hey @sperand-io, MailChimp provided some important information about this, so I'll quote here the most useful parts:

> To update the email address for a record **we would recommend creating a new record with the new email address and destroying the old one**, which is more similar to what was done on the MailChimp backend when `update_existing` was used with version 2.0 to update the email (the `euid` of subscribers would change when the email was updated).
> 
> A good workflow for this might be:
> 
> * `GET` the current data from the list members instance endpoint: `/lists/{list_id}/members/{id}`
> * `POST` this data with the updated email address to the list members collection endpoint: `/lists/{list_id}/members`
> * `DELETE` the old record from the list members instance endpoint: `/lists/{list_id}/members/{id}`
>
> [ ... ]
> 
> It's possible to keep that activity in the other email addresses record if the old email address is unsubscribed rather than deleted (since deleted subscribers are still maintained in the list database) so this might be a good option to have the ability to still reference that!

That being said, I think the best we can do is to make possible to control the subscription status using the `identify()` method.

Today your implementation always send the current subscription status, as we can see [here](https://github.com/segmentio/integration-mailchimp/blob/master/lib/index.js#L103):

```node
MailChimp.prototype.updateMember = function(basePayload, status, fn) {
  var hashedEmail = md5(basePayload.userTraits.email_address.toLowerCase());
  var endpoint = fmt('lists/%s/members/%s', basePayload.settings.listId, hashedEmail); 
  var userTraits = basePayload.userTraits;
  userTraits.status = status; // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

There's no way to send a custom `traits: { status: 'unsubscribed' }` since the `updateMember` code will overwrite it.

Maybe you can implement something like checking for a custom `subscription_status` property, and set `userTraits.status = userTraits.subscription_status || status` + unset the `userTraits.subscription_status`. Another approach to avoid compatibility issues may be requiring us to send this `status` inside a custom context exclusive for MailChimp (like we're doing for the GA `clientId`).

What do you think?

**Comment by pauloschilling** [comment]
Hi @sperand-io, @hankim813, really appreciate if you can take a look into this :) Thanks!

**Comment by hankim813** [comment]
@pauloschilling I've prioritized time tomorrow (got too much stuff today) to delve into this and ship out a resolution. Thanks for the patience!

**Comment by hankim813** [comment]
Hey @pauloschilling I'm looking at this now and again -- thanks for relaying the message from Mailchimp.

Hmm you make a good suggestion, these types of features always begs the question of spec'ing an "unsubscribe" event across email tools so that this can be done in a consistent manner across Segment vs. providing a custom exclusive context option for Mailchimp. The latter is probably short term solutions since we would prefer to the first option but that definitely takes more coordination across our different partners.

I will discuss with @sperand-io about what he thinks on this. But given your suggestion, would you send the `status: 'unsubscribed'` for the old email and then send another `.identify()` call with the proper email and exclude the `status` optional flag? 

Because this line: 

https://github.com/segmentio/integration-mailchimp/blob/master/lib/mapper.js#L36

Will just use the `userId` which I would think is the same for the two separate hypothetical `.identify()` calls. So I would think that we might have to take Mailchimp's "delete then create a new user" approach.

Let me know what you think.

**Comment by pauloschilling** [comment]
Hi @hankim813,

Today I'm already calling `.identify()` twice, like you said, the first one with the old email, and a property `newsletter: false`, and the second one with the new email and `newsletter: true`. We have this `newsletter` property mapped as a merge var on MailChimp. This is our current workaround to (un)subscribe customers.

This is bad because MailChimp charges per list member subscribed, so these old emails and the customers who have opted out through our website (`newsletter: false` property again) are still with the MC status = subscribed.

Would be really good if we can send this custom context and the desired MC `status` as follows:

* `pending`, `subscribed`, `unsubscribed`, `cleaned`: just send this status to MC instead of the current one;
* `deleted`: send a `DELETE` request to MC's API?

cc @sperand-io

Thank you, guys!

**Comment by hankim813** [comment]
Hmmm -- are you `.identify()`ing with an internal DB userId or email addresses? @pauloschilling

**Comment by pauloschilling** [comment]
Both, @hankim813, when the customer verifies the new email we store the old one as a `previous_email` DB field, since we can use this for further analysis, security and... for the first `.identify()` call, so you can hash the old email as expected.

**Comment by pauloschilling** [comment]
Like this (first identify):

```ruby
analytics.identify({
  user_id: customer.id.to_s,
  traits: {
    email: customer.previous_email,
    newsletter: false
  },
  integrations: { 'All' => false, 'MailChimp' => true }
})
```

**Comment by hankim813** [comment]
And for your second `.identify()` you are simply setting the `newsletter: true` and sending the new email? Do you keep the same `user_id`? Because the `user_id` is how we set the unique email id (euid). 

Does the second `.identify()` create a separate user for you in mailchimp?

**Comment by pauloschilling** [comment]
@hankim813, the `user_id` is always the same.

Anyway, you're setting this `payload.userTraits.unique_email_id = id` [here](https://github.com/segmentio/integration-mailchimp/blob/master/lib/mapper.js#L36) only when you create the MC list member, right?

I'm asking because when you do a `getSubscriberStatus` [here](https://github.com/segmentio/integration-mailchimp/blob/master/lib/index.js#L79), and a `updateMember` [here](https://github.com/segmentio/integration-mailchimp/blob/master/lib/index.js#L100) you have this:

```js
var hashedEmail = md5(basePayload.userTraits.email_address.toLowerCase());
var endpoint = fmt('lists/%s/members/%s', basePayload.settings.listId, hashedEmail); 
```

If I'm `.identify()`ing a cutomer to unsubscribe/delete a list member, you'll be using the *hash(old email)* to send the request.

**Comment by pauloschilling** [comment]
Also, according to https://us1.api.mailchimp.com/schema/3.0/Lists/Members/Instance.json:

```json
    "unique_email_id": {
      "type": "string",
      "title": "Unique Email ID",
      "description": "An identifier for the address across all of MailChimp.",
      "readonly": true, <<<_read_only
      "example": "5d9a5e3f7b"
    },
```

So why do you need to set the `unique_email_id`?

**Comment by hankim813** [comment]
Hey @pauloschilling, 

Had a meeting with Chris this afternoon regarding everything we've discussed in this thread so far so I wanted to update you on what we will be doing regarding this integration feature moving forward:

- We won't be providing support for updating user's email because we can't spec the `.identify()` call to listen for something like `new_email` trait and perform a look up, delete that user, and send a create request with the new email. The current `.identify()` call has no way of knowing a given email address was meant to replace the old one. This feature is a bit out of our scope. 

- We will provide the feature to manually update a user's subscription status by allowing you to send that information inside a Mailchimp exclusive context flag, similar to the `clientId` in GA's integration.

- As far as the read-only `unique_email_id`, you might be right but they also say `email_address` is read-only but we do in fact set that and that's how Mailchimp is getting their email for the users so I guess we will leave that be as long as it doesn't cause issues.

```
"email_address": {
"type": "string",
"title": "Email Address",
"description": "Email address for a subscriber.",
"readonly": true,
"example": "urist.mcvankab@freddiesjokes.com"
}
```

Does this all make sense? Let me know if you need more clarification about our reasoning here and I'll cc @sperand-io in case he wants to provide additional insights regarding our discussion.

I'll submit a separate PR for the feature support for manual updating of subscription statuses shortly.

**Comment by pauloschilling** [comment]
Hi @hankim813, @sperand-io,

Thank you so much for all the time you guys spent on this, we really, really appreciate it!

All the things you pointed out indeed make perfect sense, and the ability to change the current subscription status using a MailChimp context would be perfect, even if for some reason you decide to not implement the *"`{ status: 'deleted' }` do `DELETE` request"* thing, just the update will be enough. :)

You can count on me to test everything when you deploy the solution, or even to take a look into the PR before it goes live.

Best!

**Comment by hankim813** [comment]
@pauloschilling,

Firstly, we at Segment seriously appreciate your involvement in our product. It's pushed us to improve this integration so we are very grateful!

Yes, as far as the delete feature will go, I think that will be something that should be discussed regarding our email spec.. if we should spec that out as a semantic track event across all our partners (since most tools have APIs to delete users) vs. making that exclusive feature to Mailchimp. 

For now, this PR should do the trick for updating users' subscription statuses:

https://github.com/segmentio/integration-mailchimp/pull/24

Feel free to review this and see if you have any remarks about anything. It'll take at least one more day to get a few more eyes on this PR before we merge and push :)

**Comment by pauloschilling** [comment]
Hey @hankim813, that's exactly why I always recommend Segment to every single project around me. :)
